name: release-quics-client

on:
  workflow_dispatch:

jobs:
  release-quics-client:
    permissions:
      contents: write

    uses: ./.github/workflows/release-binary.yml
    with:
      PACKAGE_NAME: "quics-client"