name: release-quics-server

on:
  workflow_dispatch:

jobs:
  release-quics-server:
    permissions:
      contents: write

    uses: ./.github/workflows/release-binary.yml
    with:
      PACKAGE_NAME: "quics-server"